import Product from "./page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProductLayout({ children }) {
  return (
    <section>
      <Product />
    </section>
  );
}