import Busines from "./page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BusinesLayout({ children }) {
  return (
    <section>
      <Busines />
    </section>
  );
}