

import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./layout/Header";
import Footer from "./layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="  flex flex-col justify-between h-screen ">
        <div className="">
          <Header />
          <main className="max-w-[1240px] mx-auto px-[20px]  text-center align-middle mt-[130px]">{children}</main>
        </div>

        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}