import PulOtkazmalari from "./page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PulOtkazmalariLayout({ children }) {
  return (
    <section>
      <PulOtkazmalari />
    </section>
  );
}