import Tariflar from "./page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function TariflarLayout({ children }) {
  return (
    <section>
      <Tariflar />
    </section>
  );
}