import IshOrinlari from "./page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function IshOrinlariLayout({ children }) {
  return (
    <section>
      <IshOrinlari />
    </section>
  );
}