import Home from "./page";
import  Nav  from "./components/Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
   <>
    <div className="mt-[100px]">
      <Nav/>
    <section>
        {children}
    </section>
    </div>
   </>
  );
}